# -*- coding: utf-8 -*-
"""Formal typing protocol for roaster backends consumed by the Openroast UI.

Both the USB backend (freshroastsr700) and the local backend (LocalRoaster)
satisfy `RoasterProtocol` structurally — no base-class change is required.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class RoasterProtocol(Protocol):
    """Minimal interface that every roaster backend must provide.

    The USB backend exposes temperatures in Fahrenheit through ``target_temp``
    / ``current_temp`` and time through ``time_remaining`` / ``total_time``.
    """

    @property
    def connected(self) -> bool: ...

    @property
    def fan_speed(self) -> int: ...
    @fan_speed.setter
    def fan_speed(self, value: int) -> None: ...

    @property
    def heat_setting(self) -> int: ...
    @heat_setting.setter
    def heat_setting(self, value: int) -> None: ...

    @property
    def target_temp(self) -> int: ...
    @target_temp.setter
    def target_temp(self, value: int) -> None: ...

    @property
    def current_temp(self) -> int: ...

    @property
    def time_remaining(self) -> int: ...
    @time_remaining.setter
    def time_remaining(self, value: int) -> None: ...

    @property
    def total_time(self) -> int: ...
    @total_time.setter
    def total_time(self, value: int) -> None: ...

    @property
    def heater_level(self) -> int: ...

    def roast(self) -> None: ...
    def cool(self) -> None: ...
    def idle(self) -> None: ...
    def sleep(self) -> None: ...

    def set_state_transition_func(self, func) -> None: ...
    def auto_connect(self) -> None: ...
    def disconnect(self) -> None: ...


@runtime_checkable
class LocalRoasterProtocol(RoasterProtocol, Protocol):
    """Extended interface provided by the local hardware backend.

    Adds Kelvin-native temperature access, seconds-native time access,
    fault management, and runtime configuration support.
    """

    @property
    def current_temp_k(self) -> float: ...

    @property
    def target_temp_k(self) -> float: ...
    @target_temp_k.setter
    def target_temp_k(self, value: float) -> None: ...

    @property
    def time_remaining_s(self) -> int: ...
    @time_remaining_s.setter
    def time_remaining_s(self, value: int) -> None: ...

    @property
    def total_time_s(self) -> int: ...
    @total_time_s.setter
    def total_time_s(self, value: int) -> None: ...

    @property
    def fault(self) -> str | None: ...

    def clear_fault(self) -> None: ...

