"""Central parameter constants for the localroaster backend.

This module is the canonical place for backend constants that affect runtime
behavior, tuning, and simulation fidelity.
"""

# PID defaults (Celsius-domain tuning)
PID_DEFAULT_KP = 0.108
PID_DEFAULT_KI = 0.0135
PID_DEFAULT_KD = 0.018

# Control timing defaults
SAMPLE_PERIOD_DEFAULT_S = 1.0
SAMPLE_PERIOD_MIN_S = 0.01
PWM_CYCLE_DEFAULT_S = 1.0
PWM_CYCLE_MIN_S = 0.1

# Environment/safety defaults
AMBIENT_DEFAULT_K = 295.15
SAFETY_MAX_TEMP_DEFAULT_K = 560.93
MIN_DISPLAY_TEMP_DEFAULT_K = 338.71
HEATER_CUTOFF_DEFAULT_ENABLED = True

# Heater/fan/control bounds
HEATER_PERCENT_MIN = 0
HEATER_PERCENT_MAX = 100
FAN_SPEED_MAX = 1
HEAT_SETTING_MIN = 0
HEAT_SETTING_MAX = 3

# Thermostat hybrid control thresholds (Celsius error bands)
# Outside PID exit band: force full-on/full-off for fast step response.
# Inside PID enter band: hand over to PID for fine control.
THERMOSTAT_PID_ENTER_BAND_C = 3.5
THERMOSTAT_PID_EXIT_BAND_C = 5.0

# Mock simulation defaults
MOCK_THERMAL_MAX_DEFAULT_K = 560.93
MOCK_TAU_DEFAULT_S = 30.0
MOCK_FAN_COOLING_DEFAULT_K_PER_STEP = 2.0

# Autotune entry defaults
AUTOTUNE_ZN_ALPHA_DEFAULT = 0.1
AUTOTUNE_ZN_ALPHA_MIN = 0.0
AUTOTUNE_ZN_ALPHA_MAX = 1.0
AUTOTUNE_DEFAULT_STEP_PERCENT = 67
AUTOTUNE_DEFAULT_SETTLE_S = 3.0
AUTOTUNE_DEFAULT_TEST_DURATION_S = 45.0
AUTOTUNE_DEFAULT_MIN_RISE_C = 3.0

# Autotune internal limits and fallback constants
AUTOTUNE_SAMPLE_DT_MIN_S = 0.02
AUTOTUNE_TARGET_SAMPLE_DT_S = 0.2
AUTOTUNE_SETTLE_MIN_S = 0.2
AUTOTUNE_TEST_DURATION_MIN_S = 5.0
AUTOTUNE_FALLBACK_RISE_THRESHOLD_OFFSET_C = 0.5
AUTOTUNE_FALLBACK_DEAD_TIME_DEFAULT_S = 0.5
AUTOTUNE_DEAD_TIME_MIN_S = 0.2
AUTOTUNE_TAU_MIN_S = 0.2
AUTOTUNE_PROCESS_GAIN_EPS = 1e-3
AUTOTUNE_COOLING_FIT_MIN_SAMPLES = 3
AUTOTUNE_COOLING_AMBIENT_SEARCH_LOW_OFFSET_C = -30.0
AUTOTUNE_COOLING_AMBIENT_SEARCH_HIGH_OFFSET_C = 10.0
AUTOTUNE_COOLING_Y_EPS_C = 0.05
AUTOTUNE_COOLING_K_MIN_PER_S = 1e-4
AUTOTUNE_COOLING_K_MAX_PER_S = 1.0
AUTOTUNE_COOLING_AMBIENT_STEPS = 41
AUTOTUNE_COOLING_FALLBACK_K_PER_S = 0.02
AUTOTUNE_COOLING_RMSE_MAX_C = 10.0
AUTOTUNE_FOPDT_RMSE_MAX_C = 10.0

# Ziegler-Nichols reaction-curve factors
AUTOTUNE_ZN_KP_FACTOR = 1.2
AUTOTUNE_ZN_TI_FACTOR = 2.0
AUTOTUNE_ZN_TD_FACTOR = 0.5


# FOPDT fit constants
FOPDT_MAX_SAMPLES = 300
FOPDT_DEAD_TIME_MIN_S = 0.2
FOPDT_DEAD_TIME_MAX_DURATION_FACTOR = 0.6
FOPDT_DURATION_EPS = 1e-3
FOPDT_TAU_MIN_S = 0.2
FOPDT_TAU_MAX_DURATION_FACTOR = 3.0
FOPDT_DEAD_TIME_STEPS = 40
FOPDT_TAU_STEPS = 40
FOPDT_DEN_EPS = 1e-9

# Other loop timings
TIMER_ACTIVE_TICK_S = 1.0
TIMER_IDLE_POLL_S = 0.05
PWM_DELAY_MIN_S = 0.001

# PWM shape constants
PWM_DUTY_CYCLE_MIN = 0.01

